### ISSUE TITLE
Only the 2.11 builds are required for releasing

### ISSUE THREAD

**Issue by iravid** [zio/zio#1549]
The release workflow should require all builds to pass before releasing.

**Comment by ghostdogpr** [comment]
Right, just noticed this as well.

It's pretty easy, in `.circleci/config.yml`:
```
      - release_211:
          context: Sonatype
          requires:
            - test_211_jdk8_jvm
            - test_211_jdk11_jvm
            - test_211_jdk8_js
            - test_211_jdk11_js
```
All the test steps should be added here.
