### ISSUE TITLE
Use mergify to merge Steward's PR

### ISSUE THREAD

**Issue by mijicd** [zio/zio#2969]
Scala Steward is an amazing tool, but taking care of all PRs it makes throughout the organization takes a lot of time, and based on the current state, we're not coping with it successfully. I propose introducing [Mergify](https://mergify.io/) to help us with that. More information about configuring Mergify to do this can be found at [Steward's FAQ](https://github.com/fthomas/scala-steward/blob/master/docs/faq.md#how-can-scala-stewards-prs-be-merged-automatically).

**Comment by adamgfraser** [comment]
Sounds like a great idea!

**Comment by mijicd** [comment]
I'll give it a try tonight then, and propagate slowly!

**Comment by mijicd** [comment]
Mergify works very smooth in tackling PR's. For example, on `interop-monix` I've configured it using the quoted refined setup (with slight modification):

```yaml
pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [mijicd, softinio]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - 'status-success=ci/circleci: test_211_jdk8_js'
      - 'status-success=ci/circleci: test_211_jdk8_jvm'
      - 'status-success=ci/circleci: test_212_jdk8_js'
      - 'status-success=ci/circleci: test_212_jdk8_jvm'
      - 'status-success=ci/circleci: test_212_jdk11_jvm'
      - 'status-success=ci/circleci: test_213_jdk8_js'
      - 'status-success=ci/circleci: test_213_jdk8_jvm'
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: squash
        strict: true
```

This means, only patch updates will be merged automatically, while all of them will assign me and Salar to review them (if there are other volunteers, shout :)).

The downside of it is that we have to drop the required PR reviews. That being said, please say yay or nay whether to proceed.

@zio/core ^
