### ISSUE TITLE
Enabling Automerge on Pull Request Created By Github Workflows

### ISSUE THREAD

**Issue by khajavi** [zio/zio#7939]
To simplify the workflow, it's better to automatically accept and merge those pull requests made by GitHub workflows, e.g. updating docs packages.

One good option is to use [this](https://github.com/peter-evans/enable-pull-request-automerge) GitHub action.

**Comment by 987Nabil** [comment]
I think for something simple like this, you should not rely on some third party actions.
Something like this should do fine, maybe add some if condition if needed. Automerge should maybe be enabled on repo level.

```yml
  steps:
    - name: Approve
      env:
        GITHUB_TOKEN: <some token>
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: gh pr review "$PR_URL" --approve

    - name: Enable Auto-Merge
      env:
        GITHUB_TOKEN: <some token>
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: gh pr merge --auto --merge "$PR_URL" || gh pr merge --merge "$PR_URL"
```
